apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
spec:
  selector:
    matchLabels:
      app: auth-db
      tier: database
  template:
    metadata:
      labels:
        app: auth-db
        tier: database
    spec:
      containers:
        - image: docker.io/postgres:14.4-alpine3.16
        - name: auth-db
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: dbname
                  key: auth
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: authdb-pvc
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: authdb-pvc
          persistentVolumeClaim:
            claimName: authdb-claim-pvc
