// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: query.sql

package db

import (
	"context"
)

const login = `-- name: Login :one
SELECT id, username, password, email FROM auth WHERE username = $1
`

func (q *Queries) Login(ctx context.Context, username string) (Auth, error) {
	row := q.db.QueryRow(ctx, login, username)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Email,
	)
	return i, err
}
